import type { AgentAdapter } from "../types.js";

export const claudeAdapter: AgentAdapter = {
  key: "claude",
  displayName: "Claude Code",
  aliases: ["claude", "claude-code", "claudecode"],
  references: [
    "https://docs.anthropic.com/en/docs/claude-code/settings",
    "https://docs.anthropic.com/en/docs/claude-code/memory",
    "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    "https://docs.anthropic.com/en/docs/claude-code/sub-agents"
  ],
  targets: [
    {
      id: "preferences",
      label: "사용자 설정",
      description: "Claude 전역 설정 (~/.claude/settings.json)",
      category: "config",
      kind: "file",
      scope: "home",
      path: ".claude/settings.json",
      includeByDefault: true,
      structured: true,
      format: "json",
    },
    {
      id: "instructions",
      label: "지시문서",
      description: "전역 지시문서 (~/.claude/CLAUDE.md)",
      category: "instructions",
      kind: "file",
      scope: "home",
      path: ".claude/CLAUDE.md",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "skills",
      label: "스킬",
      description: "전역 스킬 디렉터리 (~/.claude/skills)",
      category: "skills",
      kind: "dir",
      scope: "home",
      path: ".claude/skills",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "sub-agents",
      label: "서브에이전트",
      description: "전역 서브에이전트 (~/.claude/agents)",
      category: "other",
      kind: "dir",
      scope: "home",
      path: ".claude/agents",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "plugins-config",
      label: "플러그인 설정",
      description: "플러그인 구성 (~/.claude/plugins/config.json)",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/config.json",
      optional: true,
      structured: true,
      format: "json",
    },
    {
      id: "plugins-installed",
      label: "플러그인 설치목록",
      description: "설치된 플러그인 메타데이터 (~/.claude/plugins/installed_plugins.json)",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/installed_plugins.json",
      optional: true,
      structured: true,
      format: "json",
    },
    {
      id: "plugins-marketplaces",
      label: "플러그인 마켓 정보",
      description: "마켓플레이스 메타데이터 (~/.claude/plugins/known_marketplaces.json)",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/known_marketplaces.json",
      optional: true,
      structured: true,
      format: "json",
    },
    {
      id: "mcp",
      label: "MCP 설정",
      description: "전역 MCP 서버 설정 (~/.claude.json, 민감정보 포함 가능)",
      category: "mcp",
      kind: "file",
      scope: "home",
      path: ".claude.json",
      optional: true,
      sensitive: true,
      structured: true,
      format: "json",
    }
  ]
};
