import type { AgentAdapter } from "../types.js";

export const claudeAdapter: AgentAdapter = {
  key: "claude",
  displayName: "Claude Code",
  aliases: ["claude", "claude-code", "claudecode"],
  references: [
    "https://docs.anthropic.com/en/docs/claude-code/settings",
    "https://docs.anthropic.com/en/docs/claude-code/memory",
    "https://docs.anthropic.com/en/docs/claude-code/slash-commands",
    "https://docs.anthropic.com/en/docs/claude-code/sub-agents"
  ],
  targets: [
    {
      id: "settings",
      label: "User settings",
      description: "~/.claude/settings.json",
      category: "config",
      kind: "file",
      scope: "home",
      path: ".claude/settings.json",
      includeByDefault: true,
    },
    {
      id: "memory-global",
      label: "Global CLAUDE.md",
      description: "~/.claude/CLAUDE.md",
      category: "instructions",
      kind: "file",
      scope: "home",
      path: ".claude/CLAUDE.md",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "skills-global",
      label: "Global skills",
      description: "~/.claude/skills",
      category: "skills",
      kind: "dir",
      scope: "home",
      path: ".claude/skills",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "agents-global",
      label: "Global sub-agents",
      description: "~/.claude/agents",
      category: "other",
      kind: "dir",
      scope: "home",
      path: ".claude/agents",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "plugins-config",
      label: "Plugin config",
      description: "~/.claude/plugins/config.json",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/config.json",
      optional: true,
    },
    {
      id: "plugins-installed",
      label: "Installed plugins metadata",
      description: "~/.claude/plugins/installed_plugins.json",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/installed_plugins.json",
      optional: true,
    },
    {
      id: "plugins-marketplaces",
      label: "Known marketplaces",
      description: "~/.claude/plugins/known_marketplaces.json",
      category: "plugins",
      kind: "file",
      scope: "home",
      path: ".claude/plugins/known_marketplaces.json",
      optional: true,
    },
    {
      id: "project-memory",
      label: "Project CLAUDE.md",
      description: "./CLAUDE.md",
      category: "instructions",
      kind: "file",
      scope: "cwd",
      path: "CLAUDE.md",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "project-claude-settings",
      label: "Project .claude/settings.json",
      description: "./.claude/settings.json",
      category: "config",
      kind: "file",
      scope: "cwd",
      path: ".claude/settings.json",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "project-mcp",
      label: "Project .mcp.json",
      description: "./.mcp.json",
      category: "mcp",
      kind: "file",
      scope: "cwd",
      path: ".mcp.json",
      optional: true,
      includeByDefault: true,
    }
  ]
};
