import type { AgentAdapter } from "../types.js";

export const opencodeAdapter: AgentAdapter = {
  key: "opencode",
  displayName: "OpenCode",
  aliases: ["opencode", "open-code", "open_code", "open code"],
  references: [
    "https://opencode.ai/docs/config/",
    "https://opencode.ai/docs/skills",
    "https://opencode.ai/docs/rules/",
    "https://opencode.ai/docs/plugins/"
  ],
  targets: [
    {
      id: "global-config",
      label: "Global config",
      description: "~/.config/opencode/opencode.json",
      category: "config",
      kind: "file",
      scope: "home",
      path: ".config/opencode/opencode.json",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "global-skills",
      label: "Global skills",
      description: "~/.config/opencode/skills",
      category: "skills",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/skills",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "global-plugins",
      label: "Global plugins",
      description: "~/.config/opencode/plugins",
      category: "plugins",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/plugins",
      optional: true,
    },
    {
      id: "global-agents-md",
      label: "Global AGENTS.md",
      description: "~/.config/opencode/AGENTS.md",
      category: "instructions",
      kind: "file",
      scope: "home",
      path: ".config/opencode/AGENTS.md",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "project-config",
      label: "Project opencode.json",
      description: "./opencode.json",
      category: "config",
      kind: "file",
      scope: "cwd",
      path: "opencode.json",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "project-opencode-dir",
      label: "Project .opencode",
      description: "./.opencode",
      category: "other",
      kind: "dir",
      scope: "cwd",
      path: ".opencode",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "project-agents-md",
      label: "Project AGENTS.md",
      description: "./AGENTS.md",
      category: "instructions",
      kind: "file",
      scope: "cwd",
      path: "AGENTS.md",
      optional: true,
      includeByDefault: true,
    }
  ]
};
