import type { AgentAdapter } from "../types.js";

export const opencodeAdapter: AgentAdapter = {
  key: "opencode",
  displayName: "OpenCode",
  aliases: ["opencode", "open-code", "open_code", "open code"],
  references: [
    "https://opencode.ai/docs/config/",
    "https://opencode.ai/docs/skills",
    "https://opencode.ai/docs/rules/",
    "https://opencode.ai/docs/plugins/"
  ],
  targets: [
    {
      id: "preferences",
      label: "사용자 설정",
      description: "OpenCode 전역 설정 (~/.config/opencode/opencode.json)",
      category: "config",
      kind: "file",
      scope: "home",
      path: ".config/opencode/opencode.json",
      optional: true,
      includeByDefault: true,
      structured: true,
      format: "json",
    },
    {
      id: "skills",
      label: "스킬",
      description: "OpenCode 전역 스킬 (~/.config/opencode/skills)",
      category: "skills",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/skills",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "plugins",
      label: "플러그인",
      description: "OpenCode 전역 플러그인 (~/.config/opencode/plugins)",
      category: "plugins",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/plugins",
      optional: true,
    },
    {
      id: "instructions",
      label: "지시문서",
      description: "OpenCode 전역 지시문서 (~/.config/opencode/AGENTS.md)",
      category: "instructions",
      kind: "file",
      scope: "home",
      path: ".config/opencode/AGENTS.md",
      optional: true,
      includeByDefault: true,
    },
    {
      id: "agents",
      label: "에이전트 프리셋",
      description: "OpenCode 전역 에이전트 (~/.config/opencode/agents)",
      category: "other",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/agents",
      optional: true,
    },
    {
      id: "commands",
      label: "커스텀 커맨드",
      description: "OpenCode 커맨드 (~/.config/opencode/commands)",
      category: "other",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/commands",
      optional: true,
    },
    {
      id: "tools",
      label: "커스텀 툴",
      description: "OpenCode 툴 정의 (~/.config/opencode/tools)",
      category: "other",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/tools",
      optional: true,
    },
    {
      id: "themes",
      label: "테마",
      description: "OpenCode 테마 (~/.config/opencode/themes)",
      category: "config",
      kind: "dir",
      scope: "home",
      path: ".config/opencode/themes",
      optional: true,
    }
  ]
};
